apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: voting-app
  labels:
    app: voting-system
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: voting-system
    component: database
