apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting-app
  labels:
    app: voting-system
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: voting-system
    component: cache
