apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting-app
  labels:
    app: voting-system
    component: result
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
    name: http
  selector:
    app: voting-system
    component: result
