apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting-app
  labels:
    app: voting-system
    component: vote
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
    name: http
  selector:
    app: voting-system
    component: vote
